---
- name: Install Docker and start Jenkins on remote host
  hosts: jenkins
  become: yes
  gather_facts: yes
  tasks:
    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      deb822_repository:
        name: docker
        types: [deb]
        uris: [https://download.docker.com/linux/ubuntu]
        suites: ["{{ ansible_facts['distribution_release'] }}"]
        components: [stable]
        architectures: [amd64]
        signed_by: /etc/apt/keyrings/docker.asc
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create jenkins_home volume if not exists
      community.docker.docker_volume:
        name: jenkins_home
        state: present

    - name: Get location of docker executable
      command:
        cmd: which docker
      register: docker_result

    - name: Start Jenkins container
      community.docker.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{ docker_result.stdout }}:/usr/bin/docker"
          - jenkins_home:/var/jenkins_home
        detach: true
      register: result
    - debug: msg={{ result.container.Id }}

    - name: Get volume info
      community.docker.docker_volume_info:
        name: jenkins_home
      register: volume_info

    - name: Get password
      slurp:
        src: "{{ volume_info.volume.Mountpoint }}/secrets/initialAdminPassword"
      register: admin_password
      retries: 20
      delay: 15
      until: admin_password is success

    - name: Print out Jenkins initial admin password
      debug:
        msg: "{{ (admin_password.content | b64decode) | trim }}"
