---
- name: Deploy app in new namespace
  hosts: localhost # executing on local connected to K8s via kubeconfig
  vars:
    eks_cluster_name: "cluster-ansible"
    namespace: "myapp"
    kubeconfig: "kubeconfig_cluster-ansible"
  
  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ kubeconfig }}"
    - name: Deploy nginx ingress controller
      kubernetes.core.helm:
        name: ingress-controller
        release_namespace: ingress
        create_namespace: true
        chart_ref: ingress-nginx/ingress-nginx
    - name: Get ECR authentication token
      shell: |
        aws ecr get-login-password --region eu-central-1 | base64 -w 0
      register: ecr_password
      environment:
        AWS_PROFILE: "{{ aws_profile | default('') }}"
    - name: Create docker config JSON
      set_fact:
        docker_config_json: |
          {
            "auths": {
              "912235389084.dkr.ecr.eu-central-1.amazonaws.com": {
                "username": "AWS",
                "password": "{{ ecr_password.stdout }}",
                "auth": "QVdTOk=="
              }
            }
          }

    - name: Deploy ECR creds
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/dockerconfigjson
          metadata:
            name: ecr-creds
            namespace: "{{ namespace }}"
          data:
            .dockerconfigjson: "{{ docker_config_json | b64encode }}"    
    - name: Deploy configmap
      kubernetes.core.k8s:
        src: k8s/db-config.yaml
        state: present
        namespace: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
    - name: Deploy secret
      kubernetes.core.k8s:
        src: k8s/db-secret.yaml
        state: present
        namespace: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
    - name: Deploy ingress
      kubernetes.core.k8s:
        src: k8s/ingress.yaml
        state: present
        namespace: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
    - name: Deploy mysql
      kubernetes.core.k8s:
        src: k8s/mysql.yaml
        state: present
        namespace: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
    - name: Deploy java app 
      kubernetes.core.k8s:
        src: java-app.yaml
        state: present
        namespace: "{{ namespace }}"
        kubeconfig: "{{ kubeconfig }}"
